name: example-environment
channels:
  - conda-forge
dependencies:
  - python=3.9.12
  - python=3.9.12
  - spacy=3.3.1
  - spacy-model-en_core_web_sm=3.3.0
  - pandas=1.4.3
  - openpyxl=3.0.9
  - nltk=3.7
  - ipywidgets=8.0.2
  - pyarrow==8.0.0
  - matplotlib
  - pip
  - jupyter_contrib_nbextensions
  - fileupload